#!/usr/bin/python3
import sys
import os
#AUTHOR: MASON DONNOHUE

lOption = True #lines
wOption = True #words
cOption = True #bytes
mOption = False #By default, 'm' (characters) is disabled.
optionsFound = False
files = []

for i in range(1, len(sys.argv)): #goes through every element in sys.argv
	if sys.argv[i][0] != "-": #if the particular element starts does not start with a dash
		files.append(sys.argv[i])
	else: #if the element starts with a dash, it is specifying options.
		if not optionsFound:
			lOption = False
			wOption = False
			cOption = False
			optionsFound = True 							
		if "l" in sys.argv[i]:
			lOption = True
		if "w" in sys.argv[i]:
			wOption = True
		if "c" in sys.argv[i]:
			cOption = True
		if "m" in sys.argv[i]:
			mOption = True
if len(files) == 0: #if the user specified no files, the program reads from standard input
	stdinpt = sys.stdin
	linect = 0
	wordct = 0
	characters = 0
	for line in stdinpt:
		linect += 1
		for word in line.split():
			wordct+=1
			for character in list(word):
				characters += 1
	#depending on what options are enabled, different counts are printed out.
	if lOption:
		print("%3d"%linect, end = " ")
	if wOption:
		print("%3d"%wordct, end = " ")
	if cOption or mOption:
		print("%3d"%characters, end = " ")
	print()
else: #if the list "files" is not empty (meaning the user specified file(s))
	for file in files:
		the_file = open(file, 'r')
		linect = 0
		wordct = 0
		characters = 0
		for line in the_file:
			linect += 1
			for word in line.split():
				wordct+=1
				for character in list(word):
					characters += 1
		if lOption:
			print("%3d"%linect, end = " ")
		if wOption:
			print("%3d"%wordct, end = " ")
		if cOption or mOption:
			print("%3d"%characters, end = " ")
		print(file)

